# Generated by Django 5.0.7 on 2024-08-06 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Foundation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('creation_date', models.DateField(verbose_name='Fecha de creación')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('focus_area', models.CharField(max_length=255, verbose_name='Área de enfoque')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitud')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitud')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administered_foundation', to=settings.AUTH_USER_MODEL, verbose_name='Administrador')),
            ],
            options={
                'verbose_name': 'Fundación',
                'verbose_name_plural': 'Fundaciones',
            },
        ),
    ]
