# Generated by Django 5.0.7 on 2024-08-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_role_customuser_role_customuser_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='roles',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('STAFF', 'Personal'), ('VOLUNTEER', 'Voluntario'), ('USER', 'Usuario Regular')], default='USER', max_length=20),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
