# Generated by Django 5.0.7 on 2024-08-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_customuser_roles_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('VOLUNTEER', 'Voluntario'), ('USER', 'Usuario Regular')], default='USER', max_length=20),
        ),
    ]
